### ISSUE TITLE
[Feature] 프로필 관련 API 작업

### ISSUE THREAD

**Issue by ymink716** [ymink716/ez-ask-backend#19]
## Description

- 프로필 관련 API 구현
- 테스트 코드 보완
- Swagger API 문서 작성
- 상수 값 정리

<br>

## Todo

- [x] Swagger 연동 및 API 문서 작성
- [x] 테스트 코드 보완
- [ ] 프로필 관련 API 구현
- [x] 상수값 정리

<br>

## Reference

- configService 모킹 : 
  - https://juneyoung.io/development-nestjs-usecase-unit-test-with-di-220320
- Health Check용 end point를 위한 global prefix 제외 설정 : 
  - https://stackoverflow.com/questions/74874316/setglobalprefix-exclude-endpoint-nestjs
- nestjs에서 pm2로 배포하는 명령어
  - https://velog.io/@seunghwa17/NestJs-pm2-%EC%A0%81%EC%9A%A9
- AMI로 인스턴스 복제하여 ELB 대상 그룹에 추가
  - https://blog.naver.com/chloemoretz2000/222669485487
- 호스트 ip 주소 얻는 방법
  - https://stackoverflow.com/questions/3653065/get-local-ip-address-in-node-js
